# 서버 포트 설정
server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1214
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# 이미지 폴더 주소 설정
#   import org.springframework.beans.factory.annotation.Value;
#   @Value("${file.spring_img}")
#   String savePath;
#
file:
  spring_img: ${user.home}\Desktop\springboot_img\